const escape=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderDemo(e:any):string{
 const proofs=e.proofs??[];
 return `<!doctype html><html lang="en"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PerpParrot — integration evidence</title><style>
body{font-family:system-ui,sans-serif;margin:0;background:#0b1421;color:#e7eef8}main{max-width:1100px;margin:auto;padding:40px 24px}h1{font-size:36px;margin-bottom:8px}p{line-height:1.65;color:#b9c9dd}.tag{display:inline-block;padding:7px 12px;border-radius:6px;background:#254538;color:#aff0cc;margin:4px 8px 4px 0}.scope{border-left:4px solid #e9b863;background:#252433;padding:16px}.flow{display:flex;gap:9px;flex-wrap:wrap;margin:26px 0}.flow span{border:1px solid #39506a;padding:15px;border-radius:8px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.card{background:#142338;padding:22px;border-radius:12px}table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;border-bottom:1px solid #314258}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:#09111d;padding:16px;border-radius:8px}summary{cursor:pointer;padding:16px 0}small{color:#9aacbe}a{color:#a9d0ff}.hash{overflow-wrap:anywhere}h2{font-size:22px;margin:12px 0}</style><main>
<small>PerpParrot · Night handoff · ${escape(e.recordedAt)}</small><h1>One pipeline. Inspectable evidence.</h1>
<p>James’s backend / executor interfaces, Masa’s Score and the team’s Review / freeze modules, exercised together.</p>
<div class="scope"><strong>Controlled integration demonstration</strong><br>Inputs and model decisions below are synthetic and deterministic. Real team modules, HTTP transport, SQL migrations and dry-run execution are used. This verifies integration and recovery; it is not a live trading result or a two-LLM performance comparison.</div>
<div class="flow">${['Score','Review + audit','Freeze + restart','Snapshot → HTTP targets','Executor dry run','Stored run → dashboard read'].map(x=>`<span>${x}</span>`).join(' → ')}</div>
<span class="tag">${escape(e.receipt.status)}</span><span class="tag">2 replaceable rule adapters</span><span class="tag">0 exchange orders submitted</span>
<div class="cards">${proofs.map((p:any)=>`<section class="card"><h2>${escape(p.algorithm)}</h2><table><tr><td>Score finalists</td><td>${p.score.finalists}</td></tr><tr><td>Review</td><td>${escape(p.reviewStatus)}</td></tr><tr><td>Persistent audit rows</td><td>${p.auditRows}</td></tr><tr><td>After freeze / reopen</td><td>${escape(p.afterFreezePhase)}</td></tr><tr><td>Planned legs</td><td>${p.serviceProof.plannedOrders}</td></tr><tr><td>Freeze retained</td><td>${p.databaseRestartVerified?'PASS':'FAIL'}</td></tr></table><p class="hash"><small>Configuration commitment<br>${escape(p.configurationHash)}</small></p><details><summary>HTTP, persistence and fault evidence</summary><pre>${escape(JSON.stringify(p.serviceProof,null,2))}</pre></details><details><summary>Persisted executor plan (synthetic $10,000 account)</summary><pre>${escape(JSON.stringify(p.serviceProof.plan,null,2))}</pre></details></section>`).join('')}</div>
<h2>Reproduce and verify</h2><p>Run <code>bun --no-env-file night-shift-integration/demo.ts</code> after installing pinned repository dependencies. Repeat: committed stages are reused. The adjacent <code>evidence.json</code> contains the full machine-readable result. GitHub’s handoff contains the separate real-data ingestion and historical replay results.</p>
<p class="hash"><small>Code digest: ${escape(e.event.codeHash)}<br>Artifact chain: ${escape(e.receipt.artifactChainHash)}<br>Logical replay time: ${new Date(e.event.bucketMs).toISOString()}</small></p><details><summary>Full provenance and receipt</summary><pre>${escape(JSON.stringify({scope:e.scope,event:e.event,receipt:e.receipt},null,2))}</pre></details></main></html>`;
}
