// Dumps what the clone-grouping reference (grouping_ref.py) needs from the 24-account sample:
// the ranked cross-pool order, every input address, and each ranked account's daily returns.
// Ranks and daily returns are checked against the original reference by the other fixtures
// (portfolio-sample.expected.json, clones.json); the reference recomputes everything after them.
//   bun test/fixtures/score/reference/dump-grouping-inputs.ts > test/fixtures/score/reference/grouping-inputs.json
import { DEFAULT_CONFIG, scoreCandidates } from "../../../../src/score";
import { dailyReturns } from "../../../../src/score/clones";
import { analyse } from "../../../../src/score/metrics";
import { sampleInputs } from "../../../score/helpers";

const result = scoreCandidates(sampleInputs);
const ranked = result.candidates.filter(({ rank }) => rank !== null);
const returns = Object.fromEntries(ranked.map(({ address }) => {
  const analysis = analyse(sampleInputs.find((input) => input.address === address)!, DEFAULT_CONFIG)!;
  return [address, [...dailyReturns(analysis)].sort(([a], [b]) => a - b)];
}));

console.log(JSON.stringify({
  note: "Generated by dump-grouping-inputs.ts from portfolio-sample.json with the default config.",
  config: {
    cloneCorrelation: DEFAULT_CONFIG.cloneCorrelation,
    minOverlapDays: DEFAULT_CONFIG.minOverlapDays,
    finalists: DEFAULT_CONFIG.finalists,
  },
  addresses: sampleInputs.map(({ address }) => address),
  ranked: ranked.map(({ address, pool }) => ({ address, pool })),
  dailyReturns: returns,
}, null, 1));
